# Generated by Django 5.2.1 on 2025-06-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_remove_book_published_year_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to='lims_app.book')),
            ],
            options={
                'unique_together': {('book', 'session_key')},
            },
        ),
    ]
