# Generated by Django 5.2.1 on 2025-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_bagitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagitem',
            options={'verbose_name': 'Bag Item', 'verbose_name_plural': 'Bag Items'},
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
