# Generated by Django 5.2.1 on 2025-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagitem',
            options={},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='due_date',
            new_name='return_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='referece_id',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Loan', 'On Loan')], default='Available', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='books',
            field=models.ManyToManyField(to='lims_app.book'),
        ),
        migrations.AddField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(default='0000', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
