# Generated by Django 5.2.1 on 2025-09-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0007_alter_bagitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagitem',
            options={'verbose_name': 'Bag Item', 'verbose_name_plural': 'Bag Items'},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='return_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='books',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='lims_app.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='referece_id',
            field=models.CharField(default='0000', max_length=200),
            preserve_default=False,
        ),
    ]
